# Generated by Django 4.1.1 on 2022-09-15 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0002_post_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_data',
            name='author',
        ),
    ]
