# Generated by Django 4.1.1 on 2022-09-15 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_remove_post_data_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_data',
            name='date',
        ),
        migrations.CreateModel(
            name='Author_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(default='Null', max_length=12)),
                ('Work_Experience', models.CharField(default='Null', max_length=100)),
                ('your_best_work', models.TextField(default='Null', max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
