# Generated by Django 4.1.1 on 2022-09-15 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0004_remove_post_data_date_author_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_data',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
