# Generated by Django 4.1.1 on 2022-09-16 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0005_post_data_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reader_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('Name', models.CharField(default='Null', max_length=12)),
                ('mobile', models.CharField(default='Null', max_length=12)),
                ('Interest', models.CharField(default='Null', max_length=100)),
                ('Location', models.CharField(default='Null', max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Reader_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
