# Generated by Django 4.1.1 on 2022-09-16 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0006_reader_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_reviewer',
            new_name='is_reader',
        ),
    ]
