# Generated by Django 4.1.1 on 2022-09-16 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0007_rename_is_reviewer_user_is_reader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reader_profile',
            name='image',
            field=models.ImageField(upload_to='profile_pics'),
        ),
    ]
